name: Debug build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
          cache: true
      - name: Build
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          go mod tidy
          CGO_ENABLED=0 go build -trimpath -ldflags "-w -s"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pkgh
          path: pkgh
